import Head from "next/head"
import { Canvas } from "@react-three/fiber"
import { Gltf } from "@react-three/drei"
import Frame from "@/components/frame"
import Rig from "@/components/rig"
import { useEffect, useState } from "react"
import Link from "next/link"
import { useRouter } from "next/router"

export default function Home() {
  const [loading, setLoading] = useState(true)
  const router = useRouter()
  const id = router.query.id

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoading(false)
    }
  }, [])

  return (
    <>
      <Head>
        <title>PPII</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!loading ? (
        <div style={{ width: "100%", height: "100vh" }}>
          {id && (
            <div
              style={{
                top: "2em",
                left: "2em",
                position: "absolute",
                zIndex: 1,
                fontFamily: "sans-serif",
              }}
            >
              <Link href="/">VOLVER</Link>
            </div>
          )}

          <Canvas
            camera={{ fov: 75, position: [0, 0, 20] }}
            eventSource={document?.getElementById("root") ?? undefined}
            eventPrefix="client"
          >
            <color attach="background" args={["#6cbabb"]} />
            <Frame
              id="01"
              name="Murcielago"
              bg="#e4cdac"
              position={[-1.1, 0.2, 0]}
              rotation={[0, 0, 0]}
              scale={0.5}
            >
              <Gltf
                src="/murcielago.glb"
                position={[2, -1.8, 0.6]}
                rotation={[0, 2.55, 0]}
                scale={4}
              />
            </Frame>
            <Frame
              id="02"
              name="PEPE II"
              bg="#e4cdac"
              scale={0.5}
              position={[0, -0.1, 0]}
            >
              <Gltf
                scale={8}
                src="/aero.glb"
                position={[-2, -5, 1]}
                rotation={[0, 2, 0]}
              />
            </Frame>
            <Frame
              id="03"
              name="Peludo"
              bg="#e4cdac"
              position={[1.1, 0.2, 0]}
              rotation={[0, 0, 0]}
              scale={0.5}
            >
              <Gltf
                scale={4}
                src="/peludo.glb"
                position={[1, -2, 1.2]}
                rotation={[0, 2.4, 0]}
              />
            </Frame>
            <Frame
              id="04"
              name="Ñandu"
              bg="#e4cdac"
              position={[-0.8, -0.9, 0]}
              rotation={[0, 0, 0]}
              scale={0.5}
            >
              <Gltf
                scale={6}
                src="/niandu.glb"
                position={[-1, -2.2, 1]}
                rotation={[0, 2.1, 0]}
              />
            </Frame>
            <Frame
              id="05"
              name="Mulita"
              bg="#e4cdac"
              position={[0.8, -0.9, 0]}
              rotation={[0, 0, 0]}
              scale={0.5}
            >
              <Gltf
                scale={6}
                src="/mulita.glb"
                position={[-1, -2.4, 1.4]}
                rotation={[0, 2.1, 0]}
              />
            </Frame>
            <Frame
              id="07"
              name="Flamenco"
              bg="#e4cdac"
              position={[0, 1, 0]}
              rotation={[0, 0, 0]}
              scale={0.5}
            >
              <Gltf
                scale={6}
                src="/flamenco.glb"
                position={[0, -3, 0.3]}
                rotation={[0, 2.1, 0]}
              />
            </Frame>
            <Rig />
          </Canvas>
        </div>
      ) : null}
    </>
  )
}
